### ISSUE TITLE
Optional Include of Current File Causes Recursion

### ISSUE THREAD

**Issue by drmmr763** [gryphonshafer/Config-App#3]
I found this out on accident and it gave my team a few hours of pain till we figured it out.

`config.yaml`
```
config: "value"
optional_include local.config.yaml
```

`local.config.yaml`
```
config: "value"
optional_include "local.config.yaml"
```

This ended up throwing errors:

```
 App.pm: Deep recursion on subroutine "Config::App::_location_fetch" at /usr/local/share/perl/5.22.1/Config/App.pm line 147.
```

That clued me into the issue and I was able to resolve it. Also it totally made sense once I realized what was happening. It would be nice if Config::App did a sanity check here when its pulling in the optional includes to make sure there isn't a recursion.

**Comment by gryphonshafer** [comment]
Wow, cool! Somebody besides me and my company and clients uses this CPAN module! I'm very pleased. Thanks for logging this issue. I think this should be an easy fix. I'll get to it in the next few days when time permits.
