### ISSUE TITLE
Should get string concat errors with bad YAML

### ISSUE THREAD

**Issue by SleepyJay** [gryphonshafer/Config-App#4]
If you have a YAML doc that doesn't parse, you get `Use of uninitialized value $_ in concatenation (.) or string at /usr/local/lib/perl5/site_perl/5.26.3/Config/App.pm line 273.`

I believe you want to be using `$error` instead of `$_` on 274.

Test:
1. Use something like this as your YAML:
```
default:
blah
 ```
2. Run something like:  `perl -e 'use Config::App'`
3. See warnings.

**Comment by gryphonshafer** [comment]
Agreed.

**Comment by gryphonshafer** [comment]
Resolved in 1e0f0ef.
